main() {
  print("This is Dart Programming Language");
  print("This is awesome");
  print("Printing something first time feels really great");
  print("This 'main' function can print very much of the code");
}

// Another way of printing

void main1() {
  var first_name = "Hello";
  var second_name = "World!";
  print("${first_name} and ${second_name}");
}

// The above method is the combination of tww to three methods
