main() {
  print("This is Dart Programming Language");
  print("This is awesome");
  print("Printing something first time feels really great");
  print("This 'main' function can print very much of the code");
}

// Another way of printing

void main1() {
  var first_name = "Hello";
  var second_name = "World!";
  print("${first_name} and ${second_name}");
}

// The above method is the combination of two to three methods

void main2() {
  var first = "You are";
  var second = "Awesome";
  print("${first} ${second}");
}

void main3() {
  var a = 1;
  var b = 2;
  var c = a + b;
  print("The sum of ${a} and ${b} is: ${c}");
}
